// <auto-generated />
using System;
using Atlantic.Pedidos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlantic.Pedidos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("IDEmpresa");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("IDTipoDocumento");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioAnulacion");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioCreacion");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("EmpresaId", "NumeroDocumento")
                        .HasDatabaseName("IX_Cliente_Empresa_Documento");

                    b.ToTable("Cliente", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMoneda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Moneda", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProducto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("IDEmpresa");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("UnidadMedidaId")
                        .HasColumnType("int")
                        .HasColumnName("IDUnidadMedida");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioCreacion");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("UnidadMedidaId");

                    b.HasIndex("EmpresaId", "CodigoProducto")
                        .HasDatabaseName("IX_Producto_Empresa_Codigo");

                    b.ToTable("Producto", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IDSucursal");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("IDEmpresa");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Sucursal", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTipoDocumento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUnidadMedida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedida", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaAnulado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("IDMoneda");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int")
                        .HasColumnName("IDSucursal");

                    b.Property<decimal>("TotalDescuentos")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalPedido")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("UsuarioAnuladoId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioAnulado");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioCreacion");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Pedido_IDCliente");

                    b.HasIndex("FechaPedido")
                        .HasDatabaseName("IX_Pedido_FechaPedido");

                    b.HasIndex("MonedaId");

                    b.HasIndex("NumeroPedido")
                        .IsUnique()
                        .HasDatabaseName("UX_Pedido_NumeroPedido");

                    b.HasIndex("SucursalId");

                    b.ToTable("Pedido", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Pedido_Anulacion", "([Estado] = 'Anulado' AND [FechaAnulado] IS NOT NULL) OR ([Estado] <> 'Anulado' AND [FechaAnulado] IS NULL)");

                            t.HasCheckConstraint("CK_Pedido_Estado", "[Estado] IN ('Registrado','Confirmado','Despachado','Entregado','Anulado')");

                            t.HasCheckConstraint("CK_Pedido_TotalPedido", "[TotalPedido] > 0");
                        });
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Pedidos.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPedidoDetalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("money");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("IDPedido");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioCreacion");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_PedidoDetalle_IDPedido");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoDetalle", "dbo");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Clave");

                    b.Property<bool?>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("IDEmpresa");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoCambiarClave")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoIntentoLogin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Usuario");

                    b.Property<int?>("NumIntentoFallidoLogin")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioCreacion");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuario_Email");

                    b.ToTable("Usuario", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Rol", "[Rol] IN ('Admin','User')");
                        });
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Cliente", b =>
                {
                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Catalogos.Producto", b =>
                {
                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Pedidos.Pedido", b =>
                {
                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Moneda");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Pedidos.PedidoDetalle", b =>
                {
                    b.HasOne("Atlantic.Pedidos.Domain.Pedidos.Pedido", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlantic.Pedidos.Domain.Catalogos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Atlantic.Pedidos.Domain.Pedidos.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
